# 차트 내장 stats 끄기(외부 statsd-exporter 사용을 위한)
statsd:
  enabled: false

# airflow가 외부 statsd-exporter로 메트릭 전송하도록 설정
# statsd_host는 실제 서비스 FQDN으로 맞춰야한다.
# cross-namespace라서 짧은 이름이 아니라 .monitoring.svc.cluster.local 까지 적어야 한다.
config:
  metrics:
    statsd_on: 'True'
    statsd_host: 'statsd-exporter-prometheus-statsd-exporter.monitoring.svc.cluster.local'
    statsd_port: '9125'
    statsd_prefix: 'airflow'

executor: "LocalExecutor"

dags:
  gitSync:
    enabled: true
    repo: https://github.com/WonYong-Jang/airflow-pipeline.git
    branch: main
    rev: HEAD
    depth: 1
    subPath: "dags"
    period: 30s


