statsd:
  udpPort: 9125          # (기본값과 동일, 명시 권장)
  mappingConfig: |
    mappings:
      - match: "airflow.dag.*.*.duration"
        name: "airflow_dag_task_duration"
        labels: { dag_id: "$1", task_id: "$2" }
      - match: "airflow.dagrun.duration.success.*"
        name: "airflow_dagrun_duration_success"
        labels: { dag_id: "$1" }
      - match: "airflow.dagrun.duration.failed.*"
        name: "airflow_dagrun_duration_failed"
        labels: { dag_id: "$1" }
      - match: "airflow.pool.open_slots.*"
        name: "airflow_pool_open_slots"
        labels: { pool: "$1" }