apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"     # statsd-exporter 다음
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  sources:
    - repoURL: https://github.com/WonYong-Jang/airflow-pipeline.git
      targetRevision: main
      ref: values
    - repoURL: https://airflow.apache.org
      chart: airflow
      targetRevision: 1.22.0
      helm:
        valueFiles:
          - $values/deploy/values/airflow.yaml
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]